### ISSUE TITLE
Update Alpine Linux 3.3 -> 3.5

### ISSUE THREAD

**Issue by devionpl** [scaleway/image-alpine#52]
Update 3.3 -> 3.5

**Comment by alexbardas** [comment]
@moul what's the status of #49. Can it be retested and merged?

**Comment by moul** [comment]
Should be good

**Comment by streaps** [comment]
-> 3.6

**Comment by sveeke** [comment]
When will the version mentioned in #49 be integrated in Scaleway itself? I installed Alpine on a x86 dedicated server today, only to find out it's ancient (3.3 with the unspported 4.5.7 kernel). 

Weirder is that when I update the image, the kernel won't update. Does anyone know how I can update the kernel to the latest kernel used by Alpine 3.6.x and why this isn't happening automatically?

Thanks in advance!

**Comment by tbillon** [comment]
For technical reasons, you have to use our kernels and not the one your distro ships. You can select your kernel by changing your bootscript in the "Advanced"  pan on the server page.

**Comment by sveeke** [comment]
Hi,

Thanks for your reply! So for technical reasons, Scaleway uses old unsupported kernels in their images? That seems like a really bad decision (both using old kernels and modifying it) from a security perspective. What changes did Scaleway make in the kernel and why are they necessary?

Too be honest, I liked the idea of Scaleway a lot, but now that I have installed Debian and Alpine images I am shocked by all the bloat and bad design choices :(. Bloated and slow MOTD's that are located at multiple places, sshd_config that follows bad practices, old unsupported modified kernels, really old versions of operating systems (Alpine), pre-installed crap (Debian) and the list goes on and on. Such a pity, because the platform is quite nice and advanced on the hardware and interface level while the prices are still okay.

How difficult is it (if it's even possible) to install custom images on Scaleway hardware? Like mounting an Alpine or Debian ISO and installing via console for example? Or using stock cloud-images. That would be an option for running our VM's.

**Comment by gardner** [comment]
@sveeke I don't know for sure but I think they have to apply custom kernel patches to work with specifics of their hardware deployments (like nbd and booting). The best place to find discussions on porting new images to Scaleway is probably by searching for "BSD Scaleway".

You probably won't get a lot of help and advice by insinuating that people are bad at their jobs in 
a github issue.

**Comment by sveeke** [comment]
@gardner Where do I insinuate that people are bad at their jobs? I merely point out that the kernel used is unsupported (which is problematic every way you look at it) and that a lot of the images on Scaleway contain bloat that is added by Scaleway since it isn't part of the official project's images. These are (I hope at least) all choices made by Scaleway and not by just 'people'.

If these images are what Scaleway wants, then the image creators (the people) are very good at their jobs. But I wasn't referring to them...

**Comment by gardner** [comment]
> Where do I insinuate that people are bad at their jobs?

here:
> That seems like a really bad decision

and here:

>  I am shocked by all the bloat and bad design choices

Perhaps it's a language issue but when I read your message you come off as an entitled jerk. It's always better to keep github issues objective. You previous message could have been more effective if written as:


> Thanks for your reply! I like Scaleway but need to use more recent kernels. What changes did Scaleway make in the kernel and why are they necessary? How difficult is it (if it's even possible) to install custom images on Scaleway hardware? Like mounting an Alpine or Debian ISO and installing via console for example? Or using stock cloud-images. That would be an option for running our VM's.

Stay frosty

**Comment by develar** [comment]
Yeach....

```
apk update
apk upgrade --available
```

and then select latest "select your kernel by changing your bootscript in the "Advanced" pan on the server page"

Docker Swarm still doesn't work for me, but at least kernel is up to date.

Bad thing is that Scaleway doesn't provide easy way to install own server (ipxe, iso as Vultr) and stock image is outdated, no docs at all (need to search by error messages and so on).

**Comment by halmartin** [comment]
A new Alpine image will be published shortly based on Alpine 3.7. We are just doing final QA on it now.

If you cannot wait, you can build it yourself from the working branch: https://github.com/scaleway/image-alpine/pull/58

**Comment by halmartin** [comment]
The new Alpine Linux 3.7 image has been published and is available for `VC1` and `C2` instances.

`VC1` instances with local boot enabled will use the default `linux-hardened` kernel available from the Alpine repository, which is a grsec kernel :slightly_smiling_face: 

`VC1` instances using a bootscript, and `C2` instances will continue to use the bootscript kernel which is not grsec.

---

Therefore, if you wish to run the grsec kernel, please use a `VC1` instance.

If you don't wish to run a grsec kernel, but still want to run a kernel from Alpine Linux, then please install `linux-vanilla` in your instance to run a mainline kernel.
