### ISSUE TITLE
No loopback

### ISSUE THREAD

**Issue by julienfr112** [scaleway/image-alpine#54]
There is no loopback on /etc/network/interfaces

Why ? It's a problem when running mongodb.

**Comment by melua** [comment]
You must manually add it to default runlevel, this is not enabled by default
`rc-update add loopback`

**Comment by marcbachmann** [comment]
What about adding it to the interfaces file?
```
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp
```

**Comment by halmartin** [comment]
I see no reason why this service can't be enabled by default, since it doesn't present any serious security risks.

We will shortly have a new image for Alpine published which includes the `loopback` service enabled by default.

I'll update this when the image is published. In the mean time, if you really want to build the new image you can do it from my branch: https://github.com/scaleway/image-alpine/pull/58
